# Generated by Django 3.0.4 on 2020-03-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_Parser', '0003_auto_20200306_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mainmodel',
            unique_together={('code', 'name')},
        ),
    ]
